version: "3.9"
services:
  mongo-ecomm:
    container_name: mongo-ecomm
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - db-mongo-ecomm:/data/db
    networks:
      - compose-bridge
    ports:
      - 27017:27017

  ecomm:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecomm:1.0
    ports:
      - 3000:3000
