openapi: "3.0.1"
info:
  title: API Ecommerce
  description: API para um ecommerce
  version: 0.0.1
  contact:
    name: Autor
    email: autor@dev.com
    url: https://mockapi.io
servers:
- url: http://localhost:3000/
paths:
  /api/categories:
    get:
      summary: Listagem de Categorias
      description: Retorna uma lista de categorias cadastradas
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
        404:
          description: Nenhuma categoria encontrada
          $ref: "#/components/responses/404NotFound"
      tags: 
       - Categories

 /api/categories/{id}:
  parameters:
  - name: id
    in: path
    schema:
      type: integer
    required: true
  get:
    summary: Exibe uma categoria a partir do ID
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      404:
      $ref: "#/components/responses/404NotFound"
    tags:
    - Category

/api/admin/categories:
  post:
    summary: Insere uma nova categoria
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              nome:
                type: string
    responses:
      201:
        description: Sucesso
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Category"
    tags:
    - Category
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        status:
          type: string

tags:
- name: Categories
  description: nome e status das categorias
- name: Category
  description: nome e status de uma única categoria